INSERT INTO SAIDA VALUES (1, 'L');
INSERT INTO SAIDA VALUES (2, 'O');
INSERT INTO SAIDA VALUES (3, 'N');
INSERT INTO SAIDA VALUES (4, 'S');

--INSERT INTO SALA VALUES (1, false, 'Sala 1');
--INSERT INTO SALA VALUES (2, false, 'Sala 2');
--INSERT INTO SALA VALUES (3, true, 'Sala 3');
--INSERT INTO SALA VALUES (4, false, 'Sala 4');
--INSERT INTO SALA VALUES (5, false, 'Sala 5');
--INSERT INTO SALA VALUES (6, false, 'Sala 6');
--INSERT INTO SALA VALUES (7, false, 'Sala 7');
--INSERT INTO SALA VALUES (8, false, 'Sala 8');
--INSERT INTO SALA VALUES (9, false, 'Sala 9');
--
--INSERT INTO SALA_SAIDA VALUES (1, 1, 1);
--INSERT INTO SALA_SAIDA VALUES (2, 4, 1);
--INSERT INTO SALA_SAIDA VALUES (3, 2, 2);
--INSERT INTO SALA_SAIDA VALUES (4, 3, 4);
--INSERT INTO SALA_SAIDA VALUES (5, 1, 4);
--INSERT INTO SALA_SAIDA VALUES (6, 4, 4);
--INSERT INTO SALA_SAIDA VALUES (7, 3, 4);
--INSERT INTO SALA_SAIDA VALUES (8, 1, 5);
--INSERT INTO SALA_SAIDA VALUES (9, 4, 5);
--INSERT INTO SALA_SAIDA VALUES (10, 2, 5);
--INSERT INTO SALA_SAIDA VALUES (11, 3, 6);
--INSERT INTO SALA_SAIDA VALUES (12, 4, 6);
--INSERT INTO SALA_SAIDA VALUES (13, 2, 6);
--INSERT INTO SALA_SAIDA VALUES (14, 3, 7);
--INSERT INTO SALA_SAIDA VALUES (15, 1, 8);
--INSERT INTO SALA_SAIDA VALUES (16, 3, 8);
--INSERT INTO SALA_SAIDA VALUES (17, 3, 9);
--INSERT INTO SALA_SAIDA VALUES (18, 2, 9);



